/******************************************************************************
* language.js                                                                 *
* Copyright 2013                                                              *
* For details about the copyright holders, see the COPYRIGHT file.            *
* This software is freely distributed under the ISC License.                  *
* For details about the license, see the LICENSE file.                        *
*                                                                             *
* This module provides an API for interacting with the language model.        *
******************************************************************************/

define([
  "jquery"
], function($) {
  var language = {};

  language.langs = {
    "include_path":"lib/codemirror-3.1/",
    "data":{
      "none":{"description":"Plain Text",
              "mode":"text/plain",
              "requires":[]},
      "asp":{"description":"ASP.NET",
             "mode":"application/x-aspx",
             "requires":["htmlmixed","clike","htmlembedded"]},
      "clike":{"file":"mode/clike/clike"},
      "c":{"description":"C",
           "mode":"text/x-csrc",
           "options":{"useCPP":true},
           "requires":["clike"]},
      "cpp":{"description":"C++",
             "mode":"text/x-c++src",
             "options":{"useCPP":true},
             "requires":["clike"]},
      "csharp":{"description":"C#",
                "mode":"text/x-csharp",
                "requires":["clike"]},
      "clojure":{"description":"Clojure",
                 "file":"mode/clojure/clojure",
                 "mode":"text/x-clojure"},
      "coffeescript":{"description":"CoffeeScript",
                      "file":"mode/coffeescript/coffeescript",
                      "mode":"text/x-coffeescript"},
      "css":{"description":"CSS",
             "file":"mode/css/css",
             "mode":"text/css"},
      "diff":{"description":"diff",
              "file":"mode/diff/diff",
              "mode":"text/x-diff"},
      "ecl":{"description":"ECL",
             "file":"mode/ecl/ecl",
             "mode":"text/x-ecl"},
      "ejs":{"description":"Embedded Javascript",
             "mode":"application/x-ejs",
             "requires":["htmlmixed","htmlembedded"]},
      "erlang":{"description":"Erlang",
                "file":"mode/erlang/erlang",
                "mode":"text/x-erlang"},
      "gfm":{"description":"Github Flavored Markdown",
             "file":"mode/gfm/gfm",
             "mode":"gfm",
             "depends":["addon/mode/overlay"],
             "requires":["markdown",
                         "asp",
                         "c",
                         "cpp",
                         "csharp",
                         "clojure",
                         "coffeescript",
                         "diff",
                         "ecl",
                         "erlang",
                         "go",
                         "groovy",
                         "haskell",
                         "haxe",
                         "html",
                         "java",
                         "javascript",
                         "jinja2",
                         "json",
                         "jsp",
                         "stex",
                         "less",
                         "lua",
                         "markdown",
                         "mysql",
                         "ntriples",
                         "ocaml",
                         "pascal",
                         "perl",
                         "php",
                         "pig",
                         "plsql",
                         "properties",
                         "python",
                         "r",
                         "rpm-spec",
                         "rpm-changes",
                         "rst",
                         "ruby",
                         "rust",
                         "scala",
                         "scheme",
                         "shell",
                         "smalltalk",
                         "smarty",
                         "sparql",
                         "stex",
                         "tiddlywiki",
                         "tikiwiki",
                         "vbscript",
                         "velocity",
                         "verilog",
                         "xml",
                         "xquery",
                         "yaml"]},
      "go":{"description":"Go",
            "file":"mode/go/go",
            "mode":"text/x-go"},
      "groovy":{"description":"Groovy",
                "file":"mode/groovy/groovy",
                "mode":"text/x-groovy"},
      "haskell":{"description":"Haskell",
                 "file":"mode/haskell/haskell",
                 "mode":"text/x-haskell"},
      "haxe":{"description":"Haxe",
              "file":"mode/haxe/haxe",
              "mode":"text/x-haxe"},
      "html":{"description":"HTML",
              "mode":"text/html",
              "requires":["xml"],
              "options":{"htmlMode":true}},
      "htmlmixed":{"description":"HTML/Javascript/CSS",
                   "file":"mode/htmlmixed/htmlmixed",
                   "mode":"text/html",
                   "requires":["xml","javascript","css"]},
      "htmlembedded":{"description":"Embedded HTML",
                      "file":"mode/htmlembedded/htmlembedded"},
      "java":{"description":"Java",
              "mode":"text/x-java",
              "requires":["clike"]},
      "javascript":{"description":"Javascript",
                    "file":"mode/javascript/javascript",
                    "mode":"text/javascript"},
      "jinja2":{"description":"Jinja2",
                "file":"mode/jinja2/jinja2",
                "mode":"jinja2"},
      "json":{"description":"JSON",
              "mode":"application/json",
              "requires":["javascript"],
              "options":{"json":true}},
      "jsp":{"description":"JSP",
             "mode":"application/x-jsp",
             "requires":["htmlmixed","clike","htmlembedded"]},
      "latex":{"requires":["stex"]},
      "less":{"description":"LESS",
              "file":"mode/less/less",
              "mode":"text/x-less"},
      "lua":{"description":"Lua",
             "file":"mode/lua/lua",
             "mode":"text/x-lua"},
      "markdown":{"description":"Markdown",
                  "file":"mode/markdown/markdown",
                  "mode":"text/x-markdown",
                  "requires":["xml"]},
      "mysql":{"description":"MySQL",
               "file":"mode/mysql/mysql",
               "mode":"text/x-mysql"},
      "ntriples":{"description":"N-Triples",
                  "file":"mode/ntriples/ntriples",
                  "mode":"text/n-triples"},
      "ocaml":{"description":"OCaml",
               "file":"mode/ocaml/ocaml",
               "mode":"text/x-ocaml"},
      "pascal":{"description":"Pascal",
                "file":"mode/pascal/pascal",
                "mode":"text/x-pascal"},
      "perl":{"description":"Perl",
              "file":"mode/perl/perl",
              "mode":"text/x-perl"},
      "php":{"description":"PHP",
             "file":"mode/php/php",
             "mode":"application/x-httpd-php",
             "requires":["xml","javascript","css","clike"]},
      "pig":{"description":"Pig Latin",
             "file":"mode/pig/pig",
             "mode":"text/x-pig"},
      "plsql":{"description":"PL/SQL",
               "file":"mode/plsql/plsql",
               "mode":"text/x-plsql"},
      "properties":{"description":"Properties file (ini)",
                    "file":"mode/properties/properties",
                    "mode":"text/x-properties"},
      "python":{"description":"Python",
                "file":"mode/python/python",
                "mode":"text/x-python"},
      "python2":{"description":"Python 2",
                 "mode":"text/x-python",
                 "requires":["python"],
                 "options":{"version":2}},
      "python3":{"description":"Python 3",
                 "mode":"text/x-python",
                 "requires":["python"],
                 "options":{"version":3}},
      "r":{"description":"R",
           "file":"mode/r/r",
           "mode":"text/x-rsrc"},
      "rpm-spec":{"description":"RPM (spec)",
                  "file":"mode/rpm/spec/spec",
                  "mode":"text/x-rpm-spec"},
      "rpm-changes":{"description":"RPM (changes)",
                     "file":"mode/rpm/changes/changes",
                     "mode":"text/x-rpm-changes"},
      "rst":{"description":"reStructuredText",
             "file":"mode/rst/rst",
             "mode":"text/x-rst"},
      "ruby":{"description":"Ruby",
              "file":"mode/ruby/ruby",
              "mode":"text/x-ruby"},
      "rust":{"description":"Rust",
              "file":"mode/rust/rust",
              "mode":"text/x-rustsrc"},
      "scala":{"description":"Scala",
               "mode":"text/x-scala",
               "requires":["clike"]},
      "scheme":{"description":"Scheme",
                "file":"mode/scheme/scheme",
                "mode":"text/x-scheme"},
      "shell":{"description":"Shell",
               "file":"mode/shell/shell",
               "mode":"text/x-sh"},
      "smalltalk":{"description":"Smalltalk",
                   "file":"mode/smalltalk/smalltalk",
                   "mode":"text/x-stsrc"},
      "smarty":{"description":"Smarty",
                "file":"mode/smarty/smarty",
                "mode":"text/x-smarty"},
      "sparql":{"description":"SPARQL",
                "file":"mode/sparql/sparql",
                "mode":"application/x-sparql-query"},
      "stex":{"description":"sTex",
              "file":"mode/stex/stex",
              "mode":"text/x-stex"},
      "tiddlywiki":{"description":"Tiddlywiki",
                    "file":"mode/tiddlywiki/tiddlywiki",
                    "mode":"text/x-tiddlywiki"},
      "tikiwiki":{"description":"Tiki wiki",
                  "file":"mode/tiki/tiki",
                  "mode":"tiki"},
      "vbscript":{"description":"VBScript",
                  "file":"mode/vbscript/vbscript",
                  "mode":"text/vbscript"},
      "velocity":{"description":"Velocity",
                  "file":"mode/velocity/velocity",
                  "mode":"text/velocity"},
      "verilog":{"description":"Verilog",
                 "file":"mode/verilog/verilog",
                 "mode":"text/x-verilog"},
      "xml":{"description":"XML",
             "file":"mode/xml/xml",
             "mode":"application/xml"},
      "xquery":{"description":"XQuery",
                "file":"mode/xquery/xquery",
                "mode":"application/xquery"},
      "yaml":{"description":"YAML",
              "file":"mode/yaml/yaml",
              "mode":"text/x-yaml"}
    }
  }

  return language;
});

/* vim: set softtabstop=2 shiftwidth=2 tabstop=8 expandtab textwidth=80: */
